language: sh 
python: "3.6.6"
cache: pip
os : windows
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
install:
  - pip install --upgrade pip wheel
  - pip install -r requirements.txt
script:
  - python test/test.py
after_success:
- coveralls
